name: german_story_app
description: اپلیکیشن آموزش آلمانی با داستان - برای تمام سطوح
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/lessons/

# برای خروجی اندروید فقط کافیست در ترمینال بزنی:
# flutter build apk --release
