// A1 ABSCHLUSSPRÜFUNG - 60 Fragen - Deutsch A1 - Full Exam
// Teil 1: Wortschatz 30 Punkte, Teil 2: Grammatik 25 Punkte, Teil 3: Lesen 10 Punkte (Total 65? But user says 60)

final Map<String, dynamic> a1_abschlusspruefung = {
  'id': 'a1',
  'title': 'Deutsch A1 Abschlussprüfung',
  'totalQuestions': 60,
  'totalPoints': 60,
  'passingScore': 36,
  'description': 'Vollständige A1 Prüfung mit Wortschatz, Grammatik und Leseverständnis',
  'parts': [
    {
      'title': 'Teil 1: Wortschatz (30 Punkte)',
      'description': 'Wähle die richtige Antwort - دایره لغات',
      'points': 30,
      'questions': [
        {
          'id': 1,
          'question': 'Wo kauft man Brot?',
          'options': ['In der Apotheke', 'In der Bäckerei', 'Im Krankenhaus', 'Im Bahnhof'],
          'answer': 'B',
          'answerText': 'In der Bäckerei',
          'explanation_de': 'Eine Bäckerei ist ein Geschäft, wo man Brot, Brötchen und Kuchen kauft.',
          'explanation_fa': 'نانوایی جایی است که نان، نان کوچک و کیک می‌فروشند.',
          'example': 'Ich kaufe Brot in der Bäckerei.',
        },
        {
          'id': 2,
          'question': 'Was ist ein Kühlschrank?',
          'options': ['Ein Gerät für kalte Lebensmittel', 'Ein Möbelstück zum Sitzen', 'Ein Raum zum Schlafen', 'Ein Fahrzeug'],
          'answer': 'A',
          'answerText': 'Ein Gerät für kalte Lebensmittel',
          'explanation_fa': 'یخچال دستگاهی برای سرد نگه داشتن مواد غذایی است.',
          'example': 'Die Milch ist im Kühlschrank.',
        },
        {
          'id': 3,
          'question': 'Was ist das Gegenteil von "teuer"?',
          'options': ['billig', 'groß', 'schön', 'schnell'],
          'answer': 'A',
          'answerText': 'billig',
          'explanation_fa': 'متضاد گران، ارزان است.',
          'example': 'Das rote Auto ist teuer, das blaue ist billig.',
        },
        {
          'id': 4,
          'question': 'Was macht man mit einem Buch?',
          'options': ['Man liest es.', 'Man fährt es.', 'Man wäscht es.', 'Man trägt es an.'],
          'answer': 'A',
          'answerText': 'Man liest es.',
          'example': 'Ich lese ein interessantes Buch.',
        },
        {
          'id': 5,
          'question': 'Wo arbeitet ein Arzt?',
          'options': ['In einer Schule', 'In einem Krankenhaus', 'In einem Supermarkt', 'In einer Bäckerei'],
          'answer': 'B',
          'answerText': 'In einem Krankenhaus',
          'example': 'Ein Arzt arbeitet im Krankenhaus.',
        },
        {
          'id': 6,
          'question': 'Was bedeutet "müde"?',
          'options': ['Man möchte schlafen.', 'Man möchte essen.', 'Man ist sehr glücklich.', 'Man ist sehr schnell.'],
          'answer': 'A',
          'answerText': 'Man möchte schlafen.',
          'example': 'Ich bin müde. Ich gehe ins Bett.',
        },
        {
          'id': 7,
          'question': 'Was trägt man im Winter?',
          'options': ['Eine Jacke', 'Einen Salat', 'Einen Teller', 'Einen Tisch'],
          'answer': 'A',
          'answerText': 'Eine Jacke',
          'example': 'Im Winter trage ich eine warme Jacke.',
        },
        {
          'id': 8,
          'question': 'Was bedeutet "der Geburtstag"?',
          'options': ['Der erste Tag der Woche', 'Der Tag, an dem man geboren wurde', 'Ein Urlaubstag', 'Ein Feiertag im Winter'],
          'answer': 'B',
          'answerText': 'Der Tag, an dem man geboren wurde',
          'example': 'Heute ist mein Geburtstag.',
        },
        {
          'id': 9,
          'question': 'Was bedeutet "anfangen"?',
          'options': ['beginnen', 'vergessen', 'verlieren', 'schließen'],
          'answer': 'A',
          'answerText': 'beginnen',
          'example': 'Der Kurs fängt um 9 Uhr an.',
        },
        {
          'id': 10,
          'question': 'Was ist "das Gemüse"?',
          'options': ['Karotten, Tomaten und Kartoffeln', 'Brot und Kuchen', 'Fisch und Fleisch', 'Wasser und Saft'],
          'answer': 'A',
          'answerText': 'Karotten, Tomaten und Kartoffeln',
          'example': 'Gemüse ist gesund. Ich esse oft Karotten und Tomaten.',
        },
        {
          'id': 11,
          'question': 'Jeden Morgen esse ich mein __________.',
          'wordBank': ['Bahnhof – Schwester – Wasser – Wohnung – lernen – Frühstück – Auto – Wochenende – Wetter – Stadt'],
          'options': ['Wetter', 'Frühstück', 'Bahnhof', 'Auto'],
          'answer': 'B',
          'answerText': 'Frühstück',
          'example': 'Jeden Morgen esse ich mein Frühstück.',
        },
        {
          'id': 12,
          'question': 'Meine __________ heißt Anna.',
          'options': ['Schwester', 'Wohnung', 'Stadt', 'Wasser'],
          'answer': 'A',
          'answerText': 'Schwester',
          'example': 'Meine Schwester heißt Anna.',
        },
        {
          'id': 13,
          'question': 'Ich fahre mit dem Zug zum __________.',
          'options': ['Wochenende', 'Bahnhof', 'Frühstück', 'Wetter'],
          'answer': 'B',
          'answerText': 'Bahnhof',
          'example': 'Ich fahre zum Bahnhof.',
        },
        {
          'id': 14,
          'question': 'Berlin ist eine große __________.',
          'options': ['Stadt', 'Schwester', 'Wohnung', 'Flasche'],
          'answer': 'A',
          'answerText': 'Stadt',
          'example': 'Berlin ist eine große Stadt.',
        },
        {
          'id': 15,
          'question': 'Am __________ habe ich frei.',
          'options': ['Auto', 'Bahnhof', 'Wochenende', 'Wasser'],
          'answer': 'C',
          'answerText': 'Wochenende',
          'example': 'Am Wochenende habe ich frei.',
        },
        {
          'id': 16,
          'question': 'Heute ist das __________ sehr schön.',
          'options': ['Wetter', 'Frühstück', 'Lernen', 'Auto'],
          'answer': 'A',
          'answerText': 'Wetter',
          'example': 'Heute ist das Wetter sehr schön.',
        },
        {
          'id': 17,
          'question': 'Ich möchte Deutsch __________.',
          'options': ['trinken', 'lernen', 'wohnen', 'fahren'],
          'answer': 'B',
          'answerText': 'lernen',
          'example': 'Ich möchte Deutsch lernen.',
        },
        {
          'id': 18,
          'question': 'Wir wohnen in einer kleinen __________.',
          'options': ['Wohnung', 'Stadt', 'Schwester', 'Straße'],
          'answer': 'A',
          'answerText': 'Wohnung',
          'example': 'Wir wohnen in einer kleinen Wohnung.',
        },
        {
          'id': 19,
          'question': 'Ich fahre mit meinem __________ zur Arbeit.',
          'options': ['Wasser', 'Auto', 'Wetter', 'Frühstück'],
          'answer': 'B',
          'answerText': 'Auto',
          'example': 'Ich fahre mit meinem Auto zur Arbeit.',
        },
        {
          'id': 20,
          'question': 'Ich trinke ein Glas __________.',
          'options': ['Stadt', 'Wohnung', 'Wasser', 'Bahnhof'],
          'answer': 'C',
          'answerText': 'Wasser',
          'example': 'Ich trinke ein Glas Wasser.',
        },
        {
          'id': 21,
          'question': 'Welches Wort gehört nicht zur Gruppe? Apfel, Banane, Orange, ...',
          'options': ['Apfel', 'Banane', 'Orange', 'Tisch'],
          'answer': 'D',
          'answerText': 'Tisch',
          'explanation_fa': 'Apfel, Banane, Orange sind Obst. Tisch ist ein Möbelstück.',
        },
        {
          'id': 22,
          'question': 'Montag, Dienstag, Januar, Mittwoch - Welches gehört nicht?',
          'options': ['Montag', 'Dienstag', 'Januar', 'Mittwoch'],
          'answer': 'C',
          'answerText': 'Januar',
          'explanation_fa': 'Montag, Dienstag, Mittwoch sind Wochentage. Januar ist ein Monat.',
        },
        {
          'id': 23,
          'question': 'Mutter, Vater, Bruder, Küche - Welches gehört nicht?',
          'options': ['Mutter', 'Vater', 'Bruder', 'Küche'],
          'answer': 'D',
          'answerText': 'Küche',
          'explanation_fa': 'Mutter, Vater, Bruder sind Familie. Küche ist ein Raum.',
        },
        {
          'id': 24,
          'question': 'laufen, schwimmen, schlafen, blau - Welches gehört nicht?',
          'options': ['laufen', 'schwimmen', 'schlafen', 'blau'],
          'answer': 'D',
          'answerText': 'blau',
          'explanation_fa': 'laufen, schwimmen, schlafen sind Verben. blau ist ein Adjektiv/Farbe.',
        },
        {
          'id': 25,
          'question': 'Hose, Jacke, Schuhe, Brot - Welches gehört nicht?',
          'options': ['Hose', 'Jacke', 'Schuhe', 'Brot'],
          'answer': 'D',
          'answerText': 'Brot',
          'explanation_fa': 'Hose, Jacke, Schuhe sind Kleidung. Brot ist Lebensmittel.',
        },
        {
          'id': 26,
          'question': 'lesen, schreiben, sprechen, Fenster - Welches gehört nicht?',
          'options': ['lesen', 'schreiben', 'sprechen', 'Fenster'],
          'answer': 'D',
          'answerText': 'Fenster',
          'explanation_fa': 'lesen, schreiben, sprechen sind Verben. Fenster ist ein Nomen.',
        },
        {
          'id': 27,
          'question': 'Arzt, Lehrer, Student, Kartoffel - Welches gehört nicht?',
          'options': ['Arzt', 'Lehrer', 'Student', 'Kartoffel'],
          'answer': 'D',
          'answerText': 'Kartoffel',
          'explanation_fa': 'Arzt, Lehrer, Student sind Berufe. Kartoffel ist Gemüse.',
        },
        {
          'id': 28,
          'question': 'Sommer, Winter, Frühling, Kaffee - Welches gehört nicht?',
          'options': ['Sommer', 'Winter', 'Frühling', 'Kaffee'],
          'answer': 'D',
          'answerText': 'Kaffee',
          'explanation_fa': 'Sommer, Winter, Frühling sind Jahreszeiten. Kaffee ist ein Getränk.',
        },
        {
          'id': 29,
          'question': 'essen, trinken, kochen, Wohnung - Welches gehört nicht?',
          'options': ['essen', 'trinken', 'kochen', 'Wohnung'],
          'answer': 'D',
          'answerText': 'Wohnung',
          'explanation_fa': 'essen, trinken, kochen sind Verben. Wohnung ist ein Nomen.',
        },
        {
          'id': 30,
          'question': 'rot, grün, schnell, blau - Welches gehört nicht?',
          'options': ['rot', 'grün', 'schnell', 'blau'],
          'answer': 'C',
          'answerText': 'schnell',
          'explanation_fa': 'rot, grün, blau sind Farben. schnell ist ein Adverb/Adjektiv für Geschwindigkeit.',
        },
      ],
    },
    {
      'title': 'Teil 2: Grammatik (25 Punkte)',
      'description': 'در این بخش، دانش گرامری شما در سطح A1 بررسی می‌شود. Themen: Präsens, Artikel, Akkusativ und Dativ, Modalverben, Perfekt, Trennbare Verben, Satzstellung, Präpositionen, Possessivartikel, Vergangenheit mit sein/haben',
      'points': 25,
      'questions': [
        {'id': 31, 'question': 'Ich ___ jeden Tag Deutsch.', 'options': ['lernen', 'lerne', 'lernt', 'gelernt'], 'answer': 'lerne', 'explanation_topic': 'Präsens - Verbkonjugation'},
        {'id': 32, 'question': 'Anna ___ in Berlin.', 'options': ['wohnen', 'wohnt', 'wohnst', 'gewohnt'], 'answer': 'wohnt', 'explanation_topic': 'Präsens - dritte Person Singular'},
        {'id': 33, 'question': 'Wir ___ morgen nach Potsdam.', 'options': ['fahren', 'fährt', 'gefahren', 'fahrt'], 'answer': 'fahren', 'explanation_topic': 'Präsens - wir Form'},
        {'id': 34, 'question': 'Ich habe ___ Bruder.', 'options': ['ein', 'einen', 'einem', 'eine'], 'answer': 'einen', 'explanation_topic': 'Akkusativ - Maskulin'},
        {'id': 35, 'question': 'Sie kauft ___ Apfel.', 'options': ['ein', 'einen', 'einem', 'einer'], 'answer': 'einen', 'explanation_topic': 'Akkusativ Artikel'},
        {'id': 36, 'question': 'Ich sehe ___ Frau.', 'options': ['die', 'der', 'den', 'das'], 'answer': 'die', 'explanation_topic': 'Akkusativ Feminin'},
        {'id': 37, 'question': 'Ich helfe ___ Mann.', 'options': ['der', 'den', 'dem', 'des'], 'answer': 'dem', 'explanation_topic': 'Dativ Maskulin'},
        {'id': 38, 'question': 'Wir sprechen mit ___ Lehrerin.', 'options': ['die', 'der', 'den', 'das'], 'answer': 'der', 'explanation_topic': 'mit + Dativ'},
        {'id': 39, 'question': 'Du ___ sehr gut Deutsch sprechen.', 'options': ['kannst', 'kann', 'können', 'gekonnt'], 'answer': 'kannst', 'explanation_topic': 'Modalverb können'},
        {'id': 40, 'question': 'Ich ___ heute nicht kommen.', 'options': ['muss', 'müssen', 'musst', 'gemusst'], 'answer': 'muss', 'explanation_topic': 'Modalverb müssen'},
        {'id': 41, 'question': 'Wir ___ morgen zusammen kochen.', 'options': ['wollen', 'will', 'wollt', 'gewollt'], 'answer': 'wollen', 'explanation_topic': 'Modalverb wollen'},
        {'id': 42, 'question': 'Ich habe gestern einen Film ___.', 'options': ['sehen', 'gesehen', 'sah', 'sieht'], 'answer': 'gesehen', 'explanation_topic': 'Perfekt mit haben'},
        {'id': 43, 'question': 'Wir sind nach Berlin ___.', 'options': ['fahren', 'gefahren', 'fuhr', 'fahrt'], 'answer': 'gefahren', 'explanation_topic': 'Perfekt mit sein'},
        {'id': 44, 'question': 'Anna hat das Buch ___.', 'options': ['lesen', 'gelesen', 'las', 'liest'], 'answer': 'gelesen', 'explanation_topic': 'Unregelmäßige Verben im Perfekt'},
        {'id': 45, 'question': 'Ich stehe jeden Morgen um 7 Uhr ___.', 'options': ['auf', 'aus', 'ein', 'geauf'], 'answer': 'auf', 'explanation_topic': 'Trennbare Verben'},
        {'id': 46, 'question': 'Er ___ am Abend seine Freunde an.', 'options': ['ruft', 'anruft', 'rufen', 'gerufen'], 'answer': 'ruft', 'explanation_topic': 'Trennbare Verben im Präsens'},
        {'id': 47, 'question': 'Morgen ___ ich meine Oma.', 'options': ['besuche', 'ich besuche', 'besucht', 'besucht habe'], 'answer': 'besuche', 'explanation_topic': 'Satzstellung mit Zeitangabe'},
        {'id': 48, 'question': 'Heute ___ ich keine Zeit.', 'options': ['habe', 'haben', 'hat', 'gehabt'], 'answer': 'habe', 'explanation_topic': 'haben im Präsens'},
        {'id': 49, 'question': 'Das Buch liegt ___ Tisch.', 'options': ['auf dem', 'auf den', 'auf der', 'auf die'], 'answer': 'auf dem', 'explanation_topic': 'Lokale Präpositionen + Dativ'},
        {'id': 50, 'question': 'Ich gehe ___ Park.', 'options': ['in den', 'im', 'in dem', 'an dem'], 'answer': 'in den', 'explanation_topic': 'Bewegung + Akkusativ'},
        {'id': 51, 'question': 'Das ist ___ Mutter.', 'options': ['ich', 'mein', 'meine', 'mich'], 'answer': 'meine', 'explanation_topic': 'Possessivartikel'},
        {'id': 52, 'question': '___ Auto ist neu.', 'options': ['Mein', 'Meine', 'Meinen', 'Meinem'], 'answer': 'Mein', 'explanation_topic': 'Possessivartikel Nominativ'},
        {'id': 53, 'question': 'Ich war gestern zu Hause. Das Verb "war" bedeutet:', 'options': ['bin gewesen', 'habe', 'werde', 'gehe'], 'answer': 'bin gewesen', 'explanation_topic': 'Präteritum von sein'},
        {'id': 54, 'question': 'Wir ___ gestern keine Zeit.', 'options': ['hatten', 'haben', 'haben gehabt', 'hat'], 'answer': 'hatten', 'explanation_topic': 'Präteritum von haben'},
        {'id': 55, 'question': '___ kommst du heute?', 'options': ['Wann', 'Wo', 'Warum', 'Wie viel'], 'answer': 'Wann', 'explanation_topic': 'Fragewörter'},
      ],
    },
    {
      'title': 'Teil 3: Lesen - Leseverständnis (10 Punkte)',
      'description': 'در این بخش، توانایی درک متن آلمانی بررسی می‌شود. هر متن را بخوانید و بهترین پاسخ را انتخاب کنید.',
      'points': 10,
      'questions': [
        {
          'id': 56,
          'text': 'Anna wohnt in Berlin. Sie arbeitet von Montag bis Freitag in einem Büro. Am Wochenende besucht sie oft ihre Familie. Am Sonntag geht sie manchmal auf den Markt und kauft Gemüse.',
          'question': 'Wo arbeitet Anna?',
          'options': ['In einem Café', 'In einem Büro', 'In einem Krankenhaus', 'In einer Schule'],
          'answer': 'In einem Büro',
          'explanation_topic': 'Lesen - Informationen finden'
        },
        {
          'id': 57,
          'text': 'Amir lernt Deutsch. Vor sechs Monaten konnte er nur wenige Wörter. Jetzt kann er schon einfache Gespräche führen. Seine Freunde Anna und Tom helfen ihm oft.',
          'question': 'Wie lange lernt Amir schon Deutsch?',
          'options': ['Seit sechs Tagen', 'Seit sechs Wochen', 'Seit sechs Monaten', 'Seit sechs Jahren'],
          'answer': 'Seit sechs Monaten',
          'explanation_topic': 'Zeitangaben verstehen'
        },
        {
          'id': 58,
          'text': 'Tom mag kein Fleisch und keinen Fisch. Deshalb kocht Amir für ihn eine Gemüsesuppe. Anna isst gern Fisch mit Reis.',
          'question': 'Was isst Tom?',
          'options': ['Fisch', 'Fleisch', 'Gemüsesuppe', 'Reis mit Fisch'],
          'answer': 'Gemüsesuppe',
          'explanation_topic': 'Negation und Informationen verbinden'
        },
        {
          'id': 59,
          'text': 'Am Samstag fahren Amir und Anna nach Potsdam. Sie besuchen ein berühmtes Schloss und machen viele Fotos. Am Nachmittag trinken sie einen Kaffee in einem Café.',
          'question': 'Was machen Amir und Anna in Potsdam?',
          'options': ['Sie arbeiten dort.', 'Sie besuchen ein Schloss.', 'Sie kaufen ein Fahrrad.', 'Sie treffen ihre Familie.'],
          'answer': 'Sie besuchen ein Schloss.',
          'explanation_topic': 'Handlungen verstehen'
        },
        {
          'id': 60,
          'text': 'Peter hat heute Geburtstag. Seine Freunde kommen am Abend zu ihm. Sie bringen Kuchen und Getränke mit.',
          'question': 'Was bringen die Freunde?',
          'options': ['Bücher und Blumen', 'Kuchen und Getränke', 'Essen aus dem Restaurant', 'Ein Fahrrad'],
          'answer': 'Kuchen und Getränke',
          'explanation_topic': 'Wortschatz im Kontext'
        },
        {
          'id': 61,
          'text': 'Liebe Maria, ich bin heute krank und bleibe zu Hause. Ich kann leider nicht zum Deutschkurs kommen. Wir sehen uns nächste Woche. Viele Grüße Anna',
          'question': 'Warum kommt Anna nicht zum Deutschkurs?',
          'options': ['Sie arbeitet.', 'Sie ist krank.', 'Sie fährt nach Berlin.', 'Sie hat keine Zeit.'],
          'answer': 'Sie ist krank.',
          'explanation_topic': 'Grund verstehen'
        },
        {
          'id': 62,
          'text': 'Im Sommer fährt Familie Müller ans Meer. Die Kinder spielen am Strand. Die Eltern schwimmen und lesen Bücher.',
          'question': 'Was machen die Kinder?',
          'options': ['Sie lesen Bücher.', 'Sie arbeiten.', 'Sie spielen am Strand.', 'Sie kochen.'],
          'answer': 'Sie spielen am Strand.',
          'explanation_topic': 'Personen und Aktivitäten zuordnen'
        },
        {
          'id': 63,
          'text': 'Amir geht morgens einkaufen. Er braucht Reis, Kräuter, Gemüse und Zitronen. Am Abend kocht er ein persisches Essen für seine Freunde.',
          'question': 'Warum kauft Amir die Zutaten?',
          'options': ['Er möchte verkaufen.', 'Er möchte kochen.', 'Er möchte reisen.', 'Er möchte lernen.'],
          'answer': 'Er möchte kochen.',
          'explanation_topic': 'Absicht erkennen'
        },
        {
          'id': 64,
          'text': 'Heute regnet es stark. Lisa bleibt zu Hause. Sie liest ein Buch und trinkt Tee. Am Abend schaut sie einen Film.',
          'question': 'Was macht Lisa am Abend?',
          'options': ['Sie geht spazieren.', 'Sie besucht Freunde.', 'Sie schaut einen Film.', 'Sie arbeitet.'],
          'answer': 'Sie schaut einen Film.',
          'explanation_topic': 'Tagesablauf verstehen'
        },
        {
          'id': 65,
          'text': 'Hallo Amir, morgen treffen wir uns um 10 Uhr vor dem Bahnhof. Wir fahren zusammen zum Markt. Bitte vergiss deinen Fahrradhelm nicht! Bis morgen! Tom',
          'question': 'Wo treffen sich Amir und Tom?',
          'options': ['Am Markt', 'Vor dem Bahnhof', 'Im Park', 'Bei Anna zu Hause'],
          'answer': 'Vor dem Bahnhof',
          'explanation_topic': 'Kurze Nachrichten verstehen'
        },
      ],
    },
  ],
  'answerKey': {
    1: 'B', 2: 'A', 3: 'A', 4: 'A', 5: 'B', 6: 'A', 7: 'A', 8: 'B', 9: 'A', 10: 'A',
    11: 'B', 12: 'A', 13: 'B', 14: 'A', 15: 'C', 16: 'A', 17: 'B', 18: 'A', 19: 'B', 20: 'C',
    21: 'D', 22: 'C', 23: 'D', 24: 'D', 25: 'D', 26: 'D', 27: 'D', 28: 'D', 29: 'D', 30: 'C',
    31: 'lerne', 32: 'wohnt', 33: 'fahren', 34: 'einen', 35: 'einen', 36: 'die', 37: 'dem', 38: 'der', 39: 'kannst', 40: 'muss',
    41: 'wollen', 42: 'gesehen', 43: 'gefahren', 44: 'gelesen', 45: 'auf', 46: 'ruft', 47: 'besuche', 48: 'habe', 49: 'auf dem', 50: 'in den',
    51: 'meine', 52: 'Mein', 53: 'bin gewesen', 54: 'hatten', 55: 'Wann',
    56: 'In einem Büro', 57: 'Seit sechs Monaten', 58: 'Gemüsesuppe', 59: 'Sie besuchen ein Schloss', 60: 'Kuchen und Getränke',
    61: 'Sie ist krank', 62: 'Sie spielen am Strand', 63: 'Er möchte kochen', 64: 'Sie schaut einen Film', 65: 'Vor dem Bahnhof',
  },
  'feedbackExample': {
    'correct': {
      'title': '✅ Richtig!',
      'example': 'Bäckerei = نانوایی\nBeispiel: Ich kaufe Brot in der Bäckerei.'
    },
    'incorrect': {
      'title': '❌ Falsch.',
      'template': 'Richtige Antwort: {answer}\nErklärung: {explanation_fa}\nBeispiel: {example}'
    }
  }
};
